// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 OxiGate contributors
//! Chat completions domain types (OpenAI-compatible).
//!
//! Request/response shapes for POST /v1/chat/completions.
//! No axum/reqwest imports — domain stays I/O-free.

use bytes::Bytes;
use serde::{Deserialize, Deserializer, Serialize, Serializer};

/// Conversation role. `Other` preserves unknown values for passthrough.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Role {
    System,
    User,
    Assistant,
    Tool,
    Other(String),
}

impl Role {
    pub fn as_str(&self) -> &str {
        match self {
            Role::System => "system",
            Role::User => "user",
            Role::Assistant => "assistant",
            Role::Tool => "tool",
            Role::Other(s) => s.as_str(),
        }
    }
}

impl std::fmt::Display for Role {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Serialize for Role {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for Role {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = String::deserialize(d)?;
        Ok(match s.as_str() {
            "system" => Role::System,
            "user" => Role::User,
            "assistant" => Role::Assistant,
            "tool" => Role::Tool,
            _ => Role::Other(s),
        })
    }
}

/// OpenAI-compatible chat completion request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatRequest {
    pub model: String,
    pub messages: Vec<Message>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_completion_tokens: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,
    /// Tools (functions) available to the model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<Tool>>,
    /// Whether the model may issue parallel tool calls in one response.
    /// Forwarded verbatim to providers that support it (OpenAI, Azure).
    /// Translation providers (Anthropic, Bedrock, Gemini) ignore this field.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parallel_tool_calls: Option<bool>,
    /// Request ID for tracing (generated by handler if absent).
    #[serde(skip)]
    pub request_id: Option<String>,
    /// Extra/unknown fields forwarded as-is to the provider.
    #[serde(flatten, default)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl ChatRequest {
    /// Returns true if the request has batch billing enabled (OpenAI batch API).
    #[must_use]
    pub fn is_batch(&self) -> bool {
        self.extra
            .get("batch")
            .and_then(|v| v.as_bool())
            .unwrap_or(false)
    }

    /// Returns a clone of this request with the model field replaced by `model`.
    ///
    /// Used by `ProviderRouter::dispatch_with_fallback` when a `FallbackTarget` specifies
    /// an explicit `model` override — the request is otherwise unchanged.
    #[must_use]
    pub fn with_model(&self, model: &str) -> Self {
        let mut cloned = self.clone();
        cloned.model = model.to_string();
        cloned
    }
}

/// Tool definition for function calling.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Tool {
    #[serde(rename = "type")]
    pub type_: String,
    pub function: ToolFunction,
}

/// Function definition within a tool.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolFunction {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

/// Tool call from model response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    pub id: String,
    #[serde(rename = "type")]
    pub type_: String,
    pub function: ToolCallFunction,
}

/// Function details in a tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallFunction {
    pub name: String,
    pub arguments: String,
}

/// A single message in the conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    pub role: Role,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<MessageContent>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
}

/// Message content: plain text or multi-modal parts.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageContent {
    Text(String),
    #[allow(dead_code)] // multi-modal parts (future-proof)
    Parts(Vec<serde_json::Value>),
}

/// OpenAI-compatible chat completion response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatResponse {
    pub id: String,
    pub object: String,
    pub created: i64,
    pub model: String,
    pub choices: Vec<Choice>,
    pub usage: Usage,
}

/// A single completion choice.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Choice {
    pub index: u32,
    pub message: Message,
    pub finish_reason: Option<String>,
}

/// Details about completion token usage (follows OpenAI convention for reasoning models).
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct CompletionTokensDetails {
    /// Thinking/reasoning tokens (Gemini 2.5 thoughts, Claude extended thinking, OpenAI o-series).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_tokens: Option<u64>,
}

/// How cache tokens relate to prompt_tokens for cost calculation .
///
/// Providers report cache usage differently. This enum makes the accounting mode explicit
/// so new providers must choose, avoiding accidental under-billing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum CacheAccounting {
    /// OpenAI: prompt_tokens is total (plain + cached); subtract cache_read to get billable input.
    #[default]
    Inclusive,
    /// Anthropic/Gemini: prompt_tokens is plain-only; cache_read is additive.
    Additive,
}

/// Details about prompt token usage (OpenAI KV-cache).
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct PromptTokensDetails {
    /// KV-cache read tokens (billed at reduced rate).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cached_tokens: Option<u64>,
}

/// Token usage from the provider response.
///
/// OpenAI-compatible fields (prompt_tokens, completion_tokens, total_tokens) are
/// serialized in the JSON response.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Usage {
    pub prompt_tokens: u64,
    pub completion_tokens: u64,
    pub total_tokens: u64,
    /// OpenAI-compatible reasoning token breakdown. Present only when the model produced
    /// thinking tokens (Gemini 2.5+, Claude extended thinking, OpenAI o-series).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completion_tokens_details: Option<CompletionTokensDetails>,
    /// Cache creation (write) input tokens (Anthropic differential pricing).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_creation_input_tokens: Option<u64>,
    /// Cache read input tokens (Anthropic differential pricing).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_read_input_tokens: Option<u64>,
    /// OpenAI prompt_tokens_details (cached_tokens for KV-cache).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompt_tokens_details: Option<PromptTokensDetails>,
    /// Tier threshold override for Gemini (input+cached for Google AI Studio).
    #[serde(skip)]
    pub tier_threshold_override: Option<u64>,
    /// How cache tokens relate to prompt_tokens (Inclusive vs Additive).
    #[serde(skip, default)]
    pub cache_accounting: CacheAccounting,
    /// Image units billed​.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image_units: Option<u64>,
    /// Audio seconds billed​.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audio_seconds: Option<f64>,
    /// Cache creation tokens with 5-minute TTL (Anthropic differential pricing).
    #[serde(default, skip_serializing_if = "u64_is_zero")]
    pub cache_creation_5m_tokens: u64,
    /// Cache creation tokens with 1-hour TTL (Anthropic differential pricing).
    #[serde(default, skip_serializing_if = "u64_is_zero")]
    pub cache_creation_1h_tokens: u64,
}

fn u64_is_zero(v: &u64) -> bool {
    *v == 0
}

/// A chunk of SSE stream data. Used for streaming chat completions.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct StreamChunk {
    /// Raw SSE data line (e.g. "data: {...}\n\n" or "data: [DONE]\n\n").
    pub data: Bytes,
    /// Usage from final chunk, when present. Enables cost header injection for streaming.
    pub usage: Option<Usage>,
    /// Resolved model name from provider chunk . First non-None wins for CostHeader::MODEL_USED.
    pub model: Option<String>,
}

impl StreamChunk {
    /// Creates a stream chunk. Use this instead of struct literal when the struct may gain
    /// fields (#[non_exhaustive]).
    #[must_use]
    pub fn new(data: Bytes, usage: Option<Usage>, model: Option<String>) -> Self {
        Self { data, usage, model }
    }
}

impl Default for StreamChunk {
    fn default() -> Self {
        Self {
            data: Bytes::new(),
            usage: None,
            model: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_usage_serialises_completion_tokens_details_when_thinking() {
        let usage = Usage {
            prompt_tokens: 10,
            completion_tokens: 5,
            total_tokens: 20,
            completion_tokens_details: Some(CompletionTokensDetails {
                reasoning_tokens: Some(5),
            }),
            prompt_tokens_details: None,
            cache_creation_input_tokens: None,
            cache_read_input_tokens: None,
            tier_threshold_override: None,
            cache_accounting: CacheAccounting::Inclusive,
            image_units: None,
            audio_seconds: None,
            cache_creation_5m_tokens: 0,
            cache_creation_1h_tokens: 0,
        };
        let json = serde_json::to_value(&usage).expect("serialise");
        assert!(json.get("completion_tokens_details").is_some());
        assert_eq!(
            json["completion_tokens_details"]["reasoning_tokens"],
            serde_json::json!(5)
        );
    }

    #[test]
    fn test_usage_omits_completion_tokens_details_when_none() {
        let usage = Usage {
            prompt_tokens: 10,
            completion_tokens: 5,
            total_tokens: 15,
            completion_tokens_details: None,
            prompt_tokens_details: None,
            cache_creation_input_tokens: None,
            cache_read_input_tokens: None,
            tier_threshold_override: None,
            cache_accounting: CacheAccounting::Inclusive,
            image_units: None,
            audio_seconds: None,
            cache_creation_5m_tokens: 0,
            cache_creation_1h_tokens: 0,
        };
        let json = serde_json::to_value(&usage).expect("serialise");
        assert!(json.get("completion_tokens_details").is_none());
    }

    /// image_units omitted when None.
    #[test]
    fn test_usage_image_units_omitted_when_none() {
        let usage = Usage {
            prompt_tokens: 10,
            completion_tokens: 5,
            total_tokens: 15,
            image_units: None,
            audio_seconds: None,
            ..Default::default()
        };
        let json = serde_json::to_value(&usage).expect("serialise");
        assert!(json.get("image_units").is_none());
    }

    /// image_units present when Some.
    #[test]
    fn test_usage_image_units_present_when_some() {
        let usage = Usage {
            prompt_tokens: 10,
            completion_tokens: 5,
            total_tokens: 15,
            image_units: Some(3),
            audio_seconds: None,
            ..Default::default()
        };
        let json = serde_json::to_value(&usage).expect("serialise");
        assert_eq!(json.get("image_units"), Some(&serde_json::json!(3)));
    }

    /// audio_seconds omitted when None.
    #[test]
    fn test_usage_audio_seconds_omitted_when_none() {
        let usage = Usage {
            prompt_tokens: 10,
            completion_tokens: 5,
            total_tokens: 15,
            image_units: None,
            audio_seconds: None,
            ..Default::default()
        };
        let json = serde_json::to_value(&usage).expect("serialise");
        assert!(json.get("audio_seconds").is_none());
    }

    /// audio_seconds present when Some.
    #[test]
    fn test_usage_audio_seconds_present_when_some() {
        let usage = Usage {
            prompt_tokens: 10,
            completion_tokens: 5,
            total_tokens: 15,
            image_units: None,
            audio_seconds: Some(5.5),
            ..Default::default()
        };
        let json = serde_json::to_value(&usage).expect("serialise");
        assert_eq!(json.get("audio_seconds"), Some(&serde_json::json!(5.5)));
    }

    #[test]
    fn test_extra_fields_forwarded() {
        let mut extra = serde_json::Map::new();
        extra.insert("custom_key".into(), serde_json::json!("custom_value"));

        let req = ChatRequest {
            model: "gpt-4".into(),
            messages: vec![Message {
                role: Role::User,
                content: Some(MessageContent::Text("Hello".into())),
                tool_calls: None,
                tool_call_id: None,
            }],
            temperature: None,
            max_tokens: None,
            max_completion_tokens: None,
            stream: None,
            tools: None,
            parallel_tool_calls: None,
            request_id: None,
            extra: extra.clone(),
        };

        let serialized = serde_json::to_value(&req).expect("serialize");
        let deserialized: ChatRequest = serde_json::from_value(serialized).expect("deserialize");
        assert_eq!(
            deserialized
                .extra
                .get("custom_key")
                .and_then(|v| v.as_str()),
            Some("custom_value")
        );
    }
}
