// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 OxiGate contributors
//! Chat completions domain types (OpenAI-compatible).
//!
//! Request/response shapes for POST /v1/chat/completions.
//! No axum/reqwest imports — domain stays I/O-free.

use bytes::Bytes;
use serde::{Deserialize, Deserializer, Serialize, Serializer};

use crate::domain::usage_accounting::CacheWriteAccounting;

/// Conversation role. `Other` preserves unknown values for passthrough.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Role {
    System,
    User,
    Assistant,
    Tool,
    Other(String),
}

impl Role {
    pub fn as_str(&self) -> &str {
        match self {
            Role::System => "system",
            Role::User => "user",
            Role::Assistant => "assistant",
            Role::Tool => "tool",
            Role::Other(s) => s.as_str(),
        }
    }
}

impl std::fmt::Display for Role {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Serialize for Role {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for Role {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = String::deserialize(d)?;
        Ok(match s.as_str() {
            "system" => Role::System,
            "user" => Role::User,
            "assistant" => Role::Assistant,
            "tool" => Role::Tool,
            _ => Role::Other(s),
        })
    }
}

/// OpenAI-compatible chat completion request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatRequest {
    pub model: String,
    pub messages: Vec<Message>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_completion_tokens: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,
    /// Tools (functions) available to the model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<Tool>>,
    /// Whether the model may issue parallel tool calls in one response.
    /// Forwarded verbatim to providers that support it (OpenAI, Azure).
    /// Translation providers (Anthropic, Bedrock, Gemini) ignore this field.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parallel_tool_calls: Option<bool>,
    /// Request ID for tracing (generated by handler if absent).
    #[serde(skip)]
    pub request_id: Option<String>,
    /// Extra/unknown fields forwarded as-is to the provider.
    #[serde(flatten, default)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl ChatRequest {
    /// Returns true if the request has batch billing enabled (OpenAI batch API).
    #[must_use]
    pub fn is_batch(&self) -> bool {
        self.extra
            .get("batch")
            .and_then(|v| v.as_bool())
            .unwrap_or(false)
    }

    /// Returns a clone of this request with the model field replaced by `model`.
    ///
    /// Used by `ProviderRouter::dispatch_with_fallback` when a `FallbackTarget` specifies
    /// an explicit `model` override — the request is otherwise unchanged.
    #[must_use]
    pub fn with_model(&self, model: &str) -> Self {
        let mut cloned = self.clone();
        cloned.model = model.to_string();
        cloned
    }
}

/// Tool definition for function calling.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Tool {
    #[serde(rename = "type")]
    pub type_: String,
    pub function: ToolFunction,
}

/// Function definition within a tool.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolFunction {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

/// Tool call from model response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    pub id: String,
    #[serde(rename = "type")]
    pub type_: String,
    pub function: ToolCallFunction,
}

/// Function details in a tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallFunction {
    pub name: String,
    pub arguments: String,
}

/// A single message in the conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    pub role: Role,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<MessageContent>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
}

/// Message content: plain text or multi-modal parts.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageContent {
    Text(String),
    #[allow(dead_code)] // multi-modal parts (future-proof)
    Parts(Vec<serde_json::Value>),
}

/// OpenAI-compatible chat completion response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatResponse {
    pub id: String,
    pub object: String,
    pub created: i64,
    pub model: String,
    pub choices: Vec<Choice>,
    pub usage: Usage,
}

/// A single completion choice.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Choice {
    pub index: u32,
    pub message: Message,
    pub finish_reason: Option<String>,
}

/// Details about completion token usage (follows OpenAI convention for reasoning models).
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct CompletionTokensDetails {
    /// Thinking/reasoning tokens (Gemini 2.5 thoughts, Claude extended thinking, OpenAI o-series).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_tokens: Option<u64>,
}

/// How cache tokens relate to prompt_tokens for cost calculation .
///
/// Providers report cache usage differently. This enum makes the accounting mode explicit
/// so new providers must choose, avoiding accidental under-billing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum CacheAccounting {
    /// `prompt_tokens` already contains the cached tokens, so every cache bucket the gateway
    /// **accounted** is carved out of it to get the billable plain input.
    ///
    /// The carve-out is driven by what a lane populated, not by what the provider's wire format
    /// can express: a bucket the lane did not account is not subtracted, because subtracting a
    /// quantity nothing priced would undercharge. Declared by OpenAI, Azure, Gemini and the
    /// generic OpenAI-compatible default — but those lanes do not populate the same buckets.
    /// Compat normalizes **cache-read only**; a third-party backend's cache-write semantics have
    /// no first-party reference, so its `cache_write_tokens` is echoed and never accounted, and
    /// nothing is carved out for it.
    #[default]
    Inclusive,
    /// `prompt_tokens` is the plain portion only; the cache buckets are reported beside it and
    /// are charged in addition to it. Declared by Anthropic and Bedrock.
    Additive,
}

/// How reasoning tokens relate to `completion_tokens` for cost calculation.
///
/// Providers differ, so the axis has to be declared rather than assumed. Pricing the reported
/// completion total *and* the reasoning breakdown at the output rate charges the reasoning subset
/// twice wherever it is already contained in that total.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ReasoningAccounting {
    /// Reasoning tokens are reported outside the completion total; charge them beside it.
    #[default]
    Additive,
    /// Reasoning tokens are already contained in the completion total; carve them out before
    /// charging the remainder at the standard output rate.
    IncludedInOutput,
}

/// The token accounting semantics of the provider contract that produced a `Usage`.
///
/// One value carries both axes so a provider contract has a single place to declare them, and so
/// a new axis cannot be added to one construction site and forgotten at another.
///
/// Both axes default to this gateway's historical behaviour, so a construction site that has not
/// been given its contract's declaration bills exactly as it did before.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct UsageAccounting {
    /// How cache tokens relate to `prompt_tokens`.
    pub cache: CacheAccounting,
    /// How reasoning tokens relate to `completion_tokens`.
    pub reasoning: ReasoningAccounting,
}

/// Details about prompt token usage (OpenAI KV-cache).
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct PromptTokensDetails {
    /// KV-cache read tokens (billed at reduced rate).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cached_tokens: Option<u64>,
    /// KV-cache write tokens — "the unadjusted number of prompt tokens written to cache".
    ///
    /// Reported inside `prompt_tokens` rather than beside it, so the quantity is a breakdown of
    /// the prompt total and not an addition to it.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_write_tokens: Option<u64>,
}

/// Token usage from the provider response.
///
/// OpenAI-compatible fields (prompt_tokens, completion_tokens, total_tokens) are
/// serialized in the JSON response.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Usage {
    pub prompt_tokens: u64,
    pub completion_tokens: u64,
    pub total_tokens: u64,
    /// OpenAI-compatible reasoning token breakdown. Present only when the model produced
    /// thinking tokens (Gemini 2.5+, Claude extended thinking, OpenAI o-series).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completion_tokens_details: Option<CompletionTokensDetails>,
    /// Accounted cache creation (write) input tokens.
    ///
    /// This is the single quantity the request is billed and budgeted on, reconciled from
    /// whatever the provider reported — aggregate, per-class details, or both. Per-class
    /// quantities are in `cache_write`; they are gateway-internal and are not published here.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_creation_input_tokens: Option<u64>,
    /// Cache read input tokens (Anthropic differential pricing).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_read_input_tokens: Option<u64>,
    /// OpenAI prompt_tokens_details (cached_tokens for KV-cache).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompt_tokens_details: Option<PromptTokensDetails>,
    /// Token accounting semantics declared by the provider contract that produced this usage.
    #[serde(skip, default)]
    pub accounting: UsageAccounting,
    /// Generalized cache-write accounting for this response, and the pricing generation the
    /// request was dispatched under.
    ///
    /// `skip` keeps it off the wire in both directions — it is gateway-internal state, not part
    /// of the OpenAI-compatible usage schema — and `default` is what keeps `Usage` deserializable
    /// without it.
    #[serde(skip, default)]
    pub cache_write: CacheWriteAccounting,
    /// Image units billed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image_units: Option<u64>,
    /// Audio seconds billed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audio_seconds: Option<f64>,
}

/// A chunk of SSE stream data. Used for streaming chat completions.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct StreamChunk {
    /// Raw SSE data line (e.g. "data: {...}\n\n" or "data: [DONE]\n\n").
    pub data: Bytes,
    /// Usage from final chunk, when present. Enables cost header injection for streaming.
    pub usage: Option<Usage>,
    /// Resolved model name from provider chunk . First non-None wins for CostHeader::MODEL_USED.
    pub model: Option<String>,
    /// Marks this chunk as the adapter's clean terminal chunk. **Required adapter contract.**
    ///
    /// Set `true` on, and only on, a chunk after which the adapter will emit no further chunks
    /// *because the upstream response completed normally*. For the OpenAI-compatible wire shape
    /// that is the chunk that **completes the `data: [DONE]` event** — the event is not dispatched
    /// until the blank line closing it, so an adapter forwarding raw bytes may find that the
    /// completing chunk carries nothing but that separator. Marking the chunk that carried the
    /// marker line instead leaves the event unterminated on the wire, and everything the gateway
    /// appends after it merges into that event.
    ///
    /// Do **not** set it on a chunk that terminates an aborted, degraded or error-interrupted
    /// stream, even when that chunk is the last one the adapter emits. Marking such a chunk
    /// asserts a completion that did not happen. A gateway-synthesized termination event —
    /// emitted because the adapter gave up rather than because the provider finished — is the
    /// in-tree example, and it deliberately leaves this flag `false`.
    ///
    /// What honouring the contract buys: the gateway schedules the request's accounting — cost
    /// computation, the cost metric, the cost log line, and the spend-record write — *before*
    /// forwarding the marked chunk, so the request is accounted even when the client stops
    /// reading at that chunk. Many HTTP clients stop reading at `data: [DONE]` and never poll the
    /// response body again.
    ///
    /// The default is `false`, so this is opt-in: an adapter that leaves it unset still works,
    /// but loses the accounting for any request whose client stops reading at its last chunk.
    ///
    /// Marking a chunk does not change where usage comes from. Accounting uses the most recent
    /// [`usage`](StreamChunk::usage) reported by *any* chunk of the stream, so a terminal chunk
    /// that carries none — a common shape, since several providers report usage on an earlier
    /// event and end with a bare terminator — is still billed from what was observed before it.
    /// Set `usage` wherever the provider actually reports it.
    pub is_final: bool,
}

impl StreamChunk {
    /// Creates a stream chunk. Use this instead of struct literal when the struct may gain
    /// fields (#[non_exhaustive]).
    ///
    /// The chunk is **not** marked terminal. An adapter marking its clean terminal chunk assigns
    /// the field after constructing:
    ///
    /// ```
    /// # use bytes::Bytes;
    /// # use oxigate::domain::chat::StreamChunk;
    /// let mut chunk = StreamChunk::new(Bytes::from_static(b"data: [DONE]\n\n"), None, None);
    /// chunk.is_final = true;
    /// ```
    ///
    /// Field assignment rather than struct-update syntax, because `#[non_exhaustive]` forbids
    /// every struct expression — `..` included — outside this crate. See
    /// [`StreamChunk::is_final`] for when marking is correct.
    #[must_use]
    pub fn new(data: Bytes, usage: Option<Usage>, model: Option<String>) -> Self {
        Self {
            data,
            usage,
            model,
            is_final: false,
        }
    }
}

impl Default for StreamChunk {
    fn default() -> Self {
        Self {
            data: Bytes::new(),
            usage: None,
            model: None,
            is_final: false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The public usage schema publishes the accounted cache-write quantity and nothing about
    /// how it was classified. Per-class quantities are gateway-internal: a client cannot depend
    /// on a class name, and adding a class cannot change the response shape.
    #[test]
    fn test_usage_publishes_only_the_accounted_cache_write_quantity() {
        let usage = Usage {
            prompt_tokens: 10,
            completion_tokens: 5,
            total_tokens: 15,
            cache_creation_input_tokens: Some(3500),
            ..Default::default()
        };
        let json = serde_json::to_string(&usage).expect("usage serialises");
        assert!(json.contains("\"cache_creation_input_tokens\":3500"));
        assert!(!json.contains("cache_creation_5m_tokens"));
        assert!(!json.contains("cache_creation_1h_tokens"));
        assert!(!json.contains("cache_write"));
    }

    #[test]
    fn test_usage_serialises_completion_tokens_details_when_thinking() {
        let usage = Usage {
            prompt_tokens: 10,
            completion_tokens: 5,
            total_tokens: 20,
            completion_tokens_details: Some(CompletionTokensDetails {
                reasoning_tokens: Some(5),
            }),
            prompt_tokens_details: None,
            cache_creation_input_tokens: None,
            cache_read_input_tokens: None,
            accounting: UsageAccounting::default(),
            image_units: None,
            audio_seconds: None,
            ..Default::default()
        };
        let json = serde_json::to_value(&usage).expect("serialise");
        assert!(json.get("completion_tokens_details").is_some());
        assert_eq!(
            json["completion_tokens_details"]["reasoning_tokens"],
            serde_json::json!(5)
        );
    }

    #[test]
    fn test_usage_omits_completion_tokens_details_when_none() {
        let usage = Usage {
            prompt_tokens: 10,
            completion_tokens: 5,
            total_tokens: 15,
            completion_tokens_details: None,
            prompt_tokens_details: None,
            cache_creation_input_tokens: None,
            cache_read_input_tokens: None,
            accounting: UsageAccounting::default(),
            image_units: None,
            audio_seconds: None,
            ..Default::default()
        };
        let json = serde_json::to_value(&usage).expect("serialise");
        assert!(json.get("completion_tokens_details").is_none());
    }

    /// The accounting defaults are this gateway's pre-existing behaviour on both axes, so an
    /// un-declared construction site cannot move a billed amount.
    #[test]
    fn test_usage_accounting_defaults_preserve_existing_behaviour() {
        let accounting = UsageAccounting::default();
        assert_eq!(accounting.cache, CacheAccounting::Inclusive);
        assert_eq!(accounting.reasoning, ReasoningAccounting::Additive);
    }

    /// `Usage::default()` carries the default accounting rather than an unset value.
    #[test]
    fn test_usage_default_carries_default_accounting() {
        assert_eq!(Usage::default().accounting, UsageAccounting::default());
    }

    /// image_units omitted when None.
    #[test]
    fn test_usage_image_units_omitted_when_none() {
        let usage = Usage {
            prompt_tokens: 10,
            completion_tokens: 5,
            total_tokens: 15,
            image_units: None,
            audio_seconds: None,
            ..Default::default()
        };
        let json = serde_json::to_value(&usage).expect("serialise");
        assert!(json.get("image_units").is_none());
    }

    /// image_units present when Some.
    #[test]
    fn test_usage_image_units_present_when_some() {
        let usage = Usage {
            prompt_tokens: 10,
            completion_tokens: 5,
            total_tokens: 15,
            image_units: Some(3),
            audio_seconds: None,
            ..Default::default()
        };
        let json = serde_json::to_value(&usage).expect("serialise");
        assert_eq!(json.get("image_units"), Some(&serde_json::json!(3)));
    }

    /// audio_seconds omitted when None.
    #[test]
    fn test_usage_audio_seconds_omitted_when_none() {
        let usage = Usage {
            prompt_tokens: 10,
            completion_tokens: 5,
            total_tokens: 15,
            image_units: None,
            audio_seconds: None,
            ..Default::default()
        };
        let json = serde_json::to_value(&usage).expect("serialise");
        assert!(json.get("audio_seconds").is_none());
    }

    /// audio_seconds present when Some.
    #[test]
    fn test_usage_audio_seconds_present_when_some() {
        let usage = Usage {
            prompt_tokens: 10,
            completion_tokens: 5,
            total_tokens: 15,
            image_units: None,
            audio_seconds: Some(5.5),
            ..Default::default()
        };
        let json = serde_json::to_value(&usage).expect("serialise");
        assert_eq!(json.get("audio_seconds"), Some(&serde_json::json!(5.5)));
    }

    #[test]
    fn test_extra_fields_forwarded() {
        let mut extra = serde_json::Map::new();
        extra.insert("custom_key".into(), serde_json::json!("custom_value"));

        let req = ChatRequest {
            model: "gpt-4".into(),
            messages: vec![Message {
                role: Role::User,
                content: Some(MessageContent::Text("Hello".into())),
                tool_calls: None,
                tool_call_id: None,
            }],
            temperature: None,
            max_tokens: None,
            max_completion_tokens: None,
            stream: None,
            tools: None,
            parallel_tool_calls: None,
            request_id: None,
            extra: extra.clone(),
        };

        let serialized = serde_json::to_value(&req).expect("serialize");
        let deserialized: ChatRequest = serde_json::from_value(serialized).expect("deserialize");
        assert_eq!(
            deserialized
                .extra
                .get("custom_key")
                .and_then(|v| v.as_str()),
            Some("custom_value")
        );
    }

    /// A chunk is not terminal unless an adapter says so. Both constructors must agree on that
    /// default: it is what lets an adapter that has never heard of the terminal-chunk contract
    /// keep compiling, at the cost of the accounting guarantee rather than at the cost of
    /// asserting a completion that never happened.
    #[test]
    fn test_stream_chunk_is_not_terminal_by_default() {
        assert!(
            !StreamChunk::default().is_final,
            "Default must not assert a completed upstream response"
        );
        assert!(
            !StreamChunk::new(Bytes::from_static(b"data: {}\n\n"), None, None).is_final,
            "new() must not assert a completed upstream response"
        );
    }
}
